### ISSUE TITLE
SyntaxError: Unexpected identifier at Jest test

### ISSUE THREAD

**Issue by Xandron3** [xlsdg/react-intl-tel-input-v2#1]
I'v got an error while trying to check component with unit tests using Jest

({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import baseGet from './_baseGet.js';

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/react-intl-tel-input-v2/dist/ReactIntlTelInput.cjs.js:8:28)

**Comment by Xandron3** [comment]
Fix: 
change
`import PhoneInput from 'react-intl-tel-input-v2';`
to 
`import PhoneInput from 'react-intl-tel-input-v2/dist/ReactIntlTelInput';`
